# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# syntax=docker/dockerfile:1

# Build stage
FROM node:lts-alpine AS build
WORKDIR /app

# Install dependencies and build tools
COPY package.json package-lock.json tsconfig.json ./
RUN apk add --no-cache python3 make g++
RUN npm install

# Copy source and patch types
COPY src ./src
# Add declaration to satisfy missing types
RUN echo "declare module 'newsapi';" > src/newsapi.d.ts

# Build TypeScript
RUN npm run build

# Production stage
FROM node:lts-alpine AS runtime
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm install --production --omit=dev
COPY --from=build /app/build ./build

EXPOSE 3333
ENTRYPOINT ["node", "build/index.js"]

